ALTER TABLE TREATMENT DROP CONSTRAINT TREATMENTpatientfk
ALTER TABLE DRUGTREATMENT DROP CONSTRAINT DRUGTREATMENT_ID
ALTER TABLE DRUGTREATMENTRECORD DROP CONSTRAINT DRGTRTMNTRCRSBJCTD
DROP TABLE PATIENT
DROP TABLE TREATMENT
DROP TABLE DRUGTREATMENT
DROP TABLE BILLINGRECORD
DROP TABLE DRUGTREATMENTRECORD
DROP TABLE SUBJECT
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
