CREATE TABLE provider (id BIGINT NOT NULL, name VARCHAR(255), npi BIGINT, provider_type INTEGER, PRIMARY KEY (id))
CREATE TABLE treatment (id BIGINT NOT NULL, DTYPE VARCHAR(31), diagnosis VARCHAR(255), treatment_type INTEGER, patient_fk BIGINT, provider_fk BIGINT, PRIMARY KEY (id))
CREATE TABLE drug_treatment (id BIGINT NOT NULL, dosage FLOAT, drug VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE surgery_treatment (id BIGINT NOT NULL, surgery_date DATE, PRIMARY KEY (id))
CREATE TABLE radiology_treatment (id BIGINT NOT NULL, PRIMARY KEY (id))
CREATE TABLE DRUGTREATMENTRECORD (ID BIGINT NOT NULL, DOSAGE FLOAT, DRUGNAME VARCHAR(255), SUBJECT_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE patient (id BIGINT NOT NULL, name VARCHAR(255), patient_id BIGINT, PRIMARY KEY (id))
CREATE TABLE BILLINGRECORD (ID  SERIAL NOT NULL, AMOUNT FLOAT, DATE DATE, DESCRIPTION VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE SUBJECT (ID  SERIAL NOT NULL, SUBJECTID BIGINT, PRIMARY KEY (ID))
CREATE TABLE provider_treatment (Provider_id BIGINT NOT NULL, treatments_id BIGINT NOT NULL, PRIMARY KEY (Provider_id, treatments_id))
CREATE TABLE RadiologyTreatment_TREATMENTDATES (RadiologyTreatment_id BIGINT, treatment_dates DATE)
CREATE TABLE patient_treatment (Patient_id BIGINT NOT NULL, treatments_id BIGINT NOT NULL, PRIMARY KEY (Patient_id, treatments_id))
ALTER TABLE treatment ADD CONSTRAINT FK_treatment_provider_fk FOREIGN KEY (provider_fk) REFERENCES provider (id)
ALTER TABLE treatment ADD CONSTRAINT FK_treatment_patient_fk FOREIGN KEY (patient_fk) REFERENCES patient (id)
ALTER TABLE drug_treatment ADD CONSTRAINT FK_drug_treatment_id FOREIGN KEY (id) REFERENCES treatment (id)
ALTER TABLE surgery_treatment ADD CONSTRAINT FK_surgery_treatment_id FOREIGN KEY (id) REFERENCES treatment (id)
ALTER TABLE radiology_treatment ADD CONSTRAINT FK_radiology_treatment_id FOREIGN KEY (id) REFERENCES treatment (id)
ALTER TABLE DRUGTREATMENTRECORD ADD CONSTRAINT FK_DRUGTREATMENTRECORD_SUBJECT_ID FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (ID)
ALTER TABLE provider_treatment ADD CONSTRAINT FK_provider_treatment_Provider_id FOREIGN KEY (Provider_id) REFERENCES provider (id)
ALTER TABLE provider_treatment ADD CONSTRAINT FK_provider_treatment_treatments_id FOREIGN KEY (treatments_id) REFERENCES treatment (id)
ALTER TABLE RadiologyTreatment_TREATMENTDATES ADD CONSTRAINT FK_RadiologyTreatment_TREATMENTDATES_RadiologyTreatment_id FOREIGN KEY (RadiologyTreatment_id) REFERENCES treatment (id)
ALTER TABLE patient_treatment ADD CONSTRAINT FK_patient_treatment_Patient_id FOREIGN KEY (Patient_id) REFERENCES patient (id)
ALTER TABLE patient_treatment ADD CONSTRAINT FK_patient_treatment_treatments_id FOREIGN KEY (treatments_id) REFERENCES treatment (id)
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
